### ISSUE TITLE
[Question] Is there a way to add anchors to headers?

### ISSUE THREAD

**Issue by eduarguz** [tighten/jigsaw-docs-template#39]
Can we extend somehow the markdown parser and add links to headers?

Like laravel docs does.

https://github.com/laravel/laravel.com-next/blob/4b4278db981cef11749dac1fce2ab538aea29f22/app/Parsedown.php#L16

Lil question so I can do that in my project and maybe we could add it to this template.

**Comment by bakerkretzmar** [comment]
You should currently be able to do this with the extended attributes syntax:

```md
## My Heading {#my-heading}
```

See https://michelf.ca/projects/php-markdown/extra/#spe-attr
